services:
  umami:
    image: ghcr.io/umami-software/umami:mysql-latest  # ✅ Use MySQL-compatible Umami image
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:QwJoUkIpbOWVCdvxzOEnwRStcNhLmzzZ@gondola.proxy.rlwy.net:43594/railway
      DATABASE_TYPE: mysql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0 
    environment:
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: QwJoUkIpbOWVCdvxzOEnwRStcNhLmzzZ
      MYSQL_ROOT_PASSWORD: QwJoUkIpbOWVCdvxzOEnwRStcNhLmzzZ
    volumes:
      - umami-db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:
